### ISSUE TITLE
[devel] Bounds & Constraints should have ID

### ISSUE THREAD

**Issue by EnricoMingo** [robotology-playground/OpenSoT#32]
As the tasks, also the bounds and the constraints should have an ID to have more information during the print out of the solver for example.

**Comment by arocchi** [comment]
In commit cdd677b (devel branch) ```Constraint``` has a new method ```std::string Constraint::getConstraintID()```

```Aggregated``` is implemented as for the task aggregated (where the final aggregated id is constructed starting from the constituting constraints id: id_1+id_2+..+id_n), ```BilateralConstraint``` allows to specify a name (since it's a generic constraint.. no unicity check as of now) and also has a counter (to have unique ids when the name is not specified)
```PositionConstraint```, ```CoMVelocity```, ```ConvexHull```, ```JointLimits```, ```SelfCollisionAvoidance```, ```Dynamics``` (torque limits), ```FrictionCone``` do not have the counter mechanism implemented, but should.
For the time being, this allows to print a "quasi-id" of constraints that provides additional information for debugging (withour resorting to RTTI)

**Comment by EnricoMingo** [comment]
Added also print out in solver. For now we can close.
